<?xml version="1.0"?>
<package format="3">
  <name>agent_client</name>
  <version>0.1.0</version>
  <description>树莓派统一多模态 Agent C++ 客户端。</description>
  <maintainer email="small-car@example.com">small_car</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <build_depend>libasound2-dev</build_depend>
  <depend>rclcpp</depend>
  <depend>rclcpp_action</depend>
  <depend>sensor_msgs</depend>
  <depend>small_car_interfaces</depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>image_transport</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>python3-yaml</exec_depend>
  <exec_depend>v4l2_camera</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
